export type ApiPaths = {
  LATEST_MEASUREMENTS_PATH?: string;
  LATEST_MEASUREMENTS_FILTERED_PATH?: string;
  AVERAGE_LATEST_MEASUREMENTS_PATH?: string;
  AVERAGE_LAST_HOUR_MEASUREMENTS_PATH?: string;
  AVERAGE_LAST_DAY_MEASUREMENTS_PATH?: string;
};
